version: '3.8'

services:

  business-central:
    image: jboss/business-central-workbench-showcase
    container_name: business-central
    ports:
    - 8080:8080
    - 8001:8001
    environment:
      - "JAVA_OPTS=-Dorg.uberfire.nio.git.hooks=/opt/jboss/wildfly/bin/.niogit/MySpace/DemoLoans.git/hooks -Ddatasource.management.disableDefaultDrivers=false"
    networks: 
      my_net:
        ipv4_address: 172.28.0.2
    volumes:
      - "~/wbgit:/opt/jboss/wildfly/bin/.niogit"
      - "~/.m2:/opt/jboss/.m2"
    
  # kie-server:
  #   image: jboss/kie-server-showcase
  #   container_name: kie-server
  #   restart: always
  #   environment:
  #     KIE_SERVER_LOCATION: http://kie-server:8080/kie-server/services/rest/server
  #     KIE_SERVER_CONTROLLER: http://business-central:8080/business-central/rest/controller
  #     KIE_MAVEN_REPO: http://business-central:8080/business-central/maven2
  #   networks: 
  #     my_net:
  #       ipv4_address: 172.28.0.3
  #   ports:
  #     - 8180:8080
  #   depends_on:
  #     - business-central

  db:
    image: mariadb
    container_name: brm-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=123123a@
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_PASSWORD=123123a@
      - MYSQL_USER=business_rule
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max-allowed-packet=1073741824
      - --wait_timeout=600
      - --net_read_timeout=600
      - --net_write_timeout=600
      - --connect_timeout=60
      - --lower_case_table_names=1
    networks:
      my_net:
        ipv4_address: 172.28.0.4
    ports:
      - 3306:3306
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    depends_on: 
      - business-central

  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    networks:
      my_net:
        ipv4_address: 172.28.0.6
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
      - ./zk-single-kafka-single/zoo1/data:/data
      - ./zk-single-kafka-single/zoo1/datalog:/datalog

  kafka1:
    image: confluentinc/cp-kafka:5.5.1
    hostname: kafka1
    networks:
      my_net:
        ipv4_address: 172.28.0.8
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./zk-single-kafka-single/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zoo1

  kafka2:
    image: confluentinc/cp-kafka:5.5.1
    hostname: kafka2
    networks:
      my_net:
        ipv4_address: 172.28.0.10
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka2:19093,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 2
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    volumes:
      - ./zk-single-kafka-multiple/kafka2/data:/var/lib/kafka/data
    depends_on:
      - zoo1

  kafka3:
    image: confluentinc/cp-kafka:5.5.1
    hostname: kafka3
    networks:
      my_net:
        ipv4_address: 172.28.0.12
    ports:
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka3:19094,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 3
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    volumes:
      - ./zk-single-kafka-multiple/kafka3/data:/var/lib/kafka/data
    depends_on:
      - zoo1

networks: 
  my_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16