version: '3.8'

services:

  business-central:
    image: jboss/business-central-workbench-showcase
    container_name: business-central
    restart: always
    ports:
    - 8080:8080
    - 8001:8001
    environment:
      - "JAVA_OPTS=-Dorg.uberfire.nio.git.hooks=/opt/jboss/wildfly/bin/.niogit/MySpace/DemoLoans.git/hooks -Ddatasource.management.disableDefaultDrivers=false"
    networks: 
      my_net:
        ipv4_address: 172.28.0.2
    volumes:
      - "~/wbgit:/opt/jboss/wildfly/bin/.niogit"
      - "~/.m2:/opt/jboss/.m2"
    
  # kie-server:
  #   image: jboss/kie-server-showcase
  #   container_name: kie-server
  #   restart: always
  #   environment:
  #     KIE_SERVER_LOCATION: http://kie-server:8080/kie-server/services/rest/server
  #     KIE_SERVER_CONTROLLER: http://business-central:8080/business-central/rest/controller
  #     KIE_MAVEN_REPO: http://business-central:8080/business-central/maven2
  #   networks: 
  #     my_net:
  #       ipv4_address: 172.28.0.3
  #   ports:
  #     - 8180:8080
  #   depends_on:
  #     - business-central

  db:
    image: mariadb
    container_name: brm-mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123123a@
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_PASSWORD=123123a@
      - MYSQL_USER=stest
    networks:
      my_net:
        ipv4_address: 172.28.0.4
    ports:
      - 3306:3306
    depends_on: 
      - business-central

networks: 
  my_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16