version: "3"

services: 
  machine0:
    image: my-alpine
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: machine0
    ports: 
      - 9870:9870
      - 9000:9090
      - 9868:9868
      - 8088:8088
    networks:
      my_net_hadoop:
        ipv4_address: 172.20.0.10
    privileged: true
    extra_hosts: 
      node-master: 172.20.0.10
      node1: 172.20.0.11
      node2: 172.20.0.12

  machine1:
    image: my-alpine
    container_name: machine1
    depends_on: 
      - machine0
    networks:
      my_net_hadoop:
        ipv4_address: 172.20.0.11
    privileged: true
    extra_hosts: 
      node-master: 172.20.0.10
      node1: 172.20.0.11
      node2: 172.20.0.12

  machine2:
    image: my-alpine
    container_name: machine2
    depends_on: 
      - machine0
    networks:
      my_net_hadoop:
        ipv4_address: 172.20.0.12
    privileged: true
    extra_hosts: 
      node-master: 172.20.0.10
      node1: 172.20.0.11
      node2: 172.20.0.12
networks: 
  my_net_hadoop:
    ipam: 
      driver: default
      config:
        - subnet: 172.20.0.0/24