version: '3.8'
services:
  db:
    image: mariadb
    container_name: my-mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123123a@
      - MYSQL_ROOT_USERNAME=mydb
      - MYSQL_PASSWORD=123123a@
      - MYSQL_USER=mydb
      - MYSQL_DATABASE=mydb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max-allowed-packet=1073741824
      - --wait_timeout=600
      - --net_read_timeout=600
      - --net_write_timeout=600
      - --connect_timeout=60
      - --lower_case_table_names=1
    networks:
      my_net_mariadb:
        ipv4_address: 172.18.0.64
    ports:
      - 3306:3306
    volumes:
      - ./init:/docker-entrypoint-initdb.d
networks: 
  my_net_mariadb:
    ipam: 
      driver: default
      config:
        - subnet: 172.18.0.0/24